### ISSUE TITLE
Failed to unmarshal json: invalid character '}' after top-level value

### ISSUE THREAD

**Issue by Pintstr** [knqyf263/crtsh#2]
after >**$ crtsh search --domain example.com**

Got this > _

> Failed to unmarshal json: invalid character '}' after top-level value

_

**Comment by Galus** [comment]
same

**Comment by Galus** [comment]
Failed to unmarshal json: unexpected end of JSON input

**Comment by ipentest** [comment]
Same with me..

Failed to unmarshal json: invalid character '}' after top-level value

**Comment by k4nfr3** [comment]
same for me. Running the windows compiled version

**Comment by redtux** [comment]
The screenshots look nice. :tada: Seems like the output could even be used in markdown tables.

Unfortunately, I get a similar error on Ubuntu 20.04.1 LTS (focal). The help is working, so it has to do with parsing, I guess. Maybe the crt.sh API has changed?

```sh
crtsh search -q Facebook
Failed to unmarshal json: unexpected end of JSON input
```

```sh
crtsh search -d %.example.com
Failed to unmarshal json: unexpected end of JSON input
```

```sh
crtsh search --domain %.example.com
Failed to unmarshal json: unexpected end of JSON input
```

**Comment by rudSarkar** [comment]
@knqyf263 Can you please respond? we all are waiting.

**Comment by knqyf263** [comment]
#1 should have fixed this issue.
